### ISSUE TITLE
兄弟牛批 地表最强

### ISSUE THREAD

**Issue by sevensky** [1061750360/chrome-plugins#1]
`
function changeImgSize(callback) {
    var childNode = $('.editor-bottom .eui-buttons-bar')[0].children[4] ;  // 这里要更新下。 
`

**Comment by 1061750360** [comment]
> function changeImgSize(callback) { var childNode = $('.editor-bottom .eui-buttons-bar')[0].children[4] ;

两年前随便写的，还有人看到呢0.0

**Comment by 1061750360** [comment]
> `function changeImgSize(callback) { var childNode = $('.editor-bottom .eui-buttons-bar')[0].children[4] ; // 这里要更新下。 `

已经改了
